# Generated by Django 5.1.6 on 2025-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='companions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.UUIDField(auto_created=True, default=True, primary_key=True, serialize=False),
        ),
    ]
