# Generated by Django 5.1.6 on 2025-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_companions_alter_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.UUIDField(auto_created=True, default=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
